---
title: "Overview"
output:  html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rvest)
library(tm)
library(wordcloud)
library(rvest)
```

# UW 410 - Applied Machine Learning

```{r, echo=FALSE}
url<- read_html("https://en.wikipedia.org/wiki/Machine_learning")
nodes<-html_nodes(x=url, css="#mw-content-text")
texts <-html_text(nodes)
pal <- brewer.pal(11, "Spectral")
pal <- pal[-(4:5)]
corp = paste(texts,collapse=" ")
wordcloud(corp, colors=pal, max.words=100, min.freq=5,ordered.colors=F)
```

## Module Overview:
+ Module 1 - [Generalized Linear Models](https://jdonaldson.github.io/uw-mlearn410/module1/linearModels.html) 
+ Module 2 - [Trees and Forests](https://jdonaldson.github.io/uw-mlearn410/module2/Trees.html) 
+ Module 3 - [Clustering](https://jdonaldson.github.io/uw-mlearn410/module3/Clustering.html) 
+ Module 4 - [Dimensionality Reduction](https://jdonaldson.github.io/uw-mlearn410/module4/DimensionalityReduction2017-03-20.pptx) 
+ Module 6 - [Recommender Systems](https://jdonaldson.github.io/uw-mlearn410/module6/RecSys.html)

## Homework : 
+ Homework 1 - [Supervised Learning](https://jdonaldson.github.io/uw-mlearn410/homework/homework1.nb.html)
